# Generated by Django 4.0.2 on 2023-05-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_changelog_isnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='test',
            field=models.TextField(default='new', verbose_name='new'),
        ),
    ]
