# Generated by Django 4.0.2 on 2023-05-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_changelog_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='test',
        ),
    ]
